import Head from "next/head";
import { Col, Row, Card, CardBody, CardTitle } from "reactstrap";

export default function Home() {

  return (
    <div>
      <Head>
        <title>FRYNET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/***Sales & Feed***/}
        <Row>
          <Card>
            <CardTitle tag="h6" className="border-bottom p-3 mb-0">
              <i className="bi bi-bell me-2"> </i>
              Analytics
            </CardTitle>
            <CardBody className="">
              <div className="mt-3">
                <h6>Store Comparison</h6>
                <img src="store-comparison.png" width={"100%"} />
                <h6>Cycles Per Error</h6>
                <img src="Cycles-per-error.png" width={"100%"} />
              </div>
            </CardBody>
          </Card>
        </Row>
      </div>
    </div>
  );
}
