import Head from "next/head";
import { Col, Row } from "reactstrap";
import LocationsChart from "../src/components/dashboard/LocationsChart";
import Feeds from "../src/components/dashboard/Feeds";
import ProjectTables from "../src/components/dashboard/ProjectTable";
import TopCards from "../src/components/dashboard/TopCards";
import { useEffect } from "react";
import useSWR from "swr";
import { fetcher } from "/lib/fetcher";

export default function Home() {

  const { data } = useSWR("/api/location?type=all", fetcher);

  useEffect(() => {
    console.log(data);
  }, [data])

  return (
    <div>
      <Head>
        <title>FRYNET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
 
        {/***Sales & Feed***/}
        <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            <LocationsChart fryerLocation={data} />
          </Col>
          {/* <Col sm="12" lg="6" xl="5" xxl="4">
            <Feeds />
          </Col> */}
        </Row>
        <Row>
          <Col lg="12" sm="12">
            <ProjectTables />
          </Col>
        </Row>
        
      </div>
    </div>
  );
}
